# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="homingexperience"
version="${file.jarVersion}"
displayName="Homing Experience"
credits="Inspired by Homing Exp Orbs by BlackoutRoulette"
authors="aaronhowser1"
description='''
Example mod that uses Kotlin for Forge.
'''
[[dependencies.homingexperience]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.homingexperience]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
